name: floi
screenshots:
  path: "foii-screenshot.png"

description: "An easy-to-grasp menstrual cycle tracking app that helps users monitor menstrual cycle and fertility."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  intl: 
  collection: ^1.17.0
  shared_preferences:
  smooth_page_indicator: ^1.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: 
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/icons/