// lib/services/localization/app_localizations.dart

import 'package:floi/utils/constants/strings.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  // Translation maps for each language
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'appName': 'Floii',
      'appTagline': 'Track your cycle with ease',
      'home': 'Home',
      'insights': 'Insights',
      'settings': 'Settings',
      'history': 'History',
      'currentPhase': 'Current Phase',
      'phase': 'Phase',
      'current': 'Current',
      'nextPeriod': 'Next Period',
      'cycleProgress': 'Cycle Progress',
      'cycle': 'Cycle',
      'Day': 'Day',
      'of': 'of',
      'left': 'left',
      'clear': 'clear',
      'Upcoming': 'Upcoming',
      'duration': 'Duration',
      'menstrualPhase': 'Menstrual',
      'follicularPhase': 'Follicular',
      'ovulationPhase': 'Ovulation',
      'lutealPhase': 'Luteal',
      'menstrualDescription': 'Food cravings and fatigue possible',
      'follicularDescription': 'Productivity and creativity possible',
      'ovulationDescription': 'Peak fertility and energy possible',
      'lutealDescription': 'Mood swings & sensitivity possible',
      'nullDescription': 'Track your cycle for personalized insights',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'accept': 'Accept',
      'trackToday': 'Track Today',
      'trackMyPeriod': 'Track My Period',
      'confirmPrediction': 'Confirm Prediction',
      'acceptPredictedPeriod': 'Accept predicted period starting from {date}?',
      'startPeriod': 'Start Period?',
      'startPeriodMessage': 'Did your period start on {date}?',
      'editPeriod': 'Edit Period',
      'periodSettings': 'Period Settings',
      'menstrualDaysQuestion': 'How many days does your typical period last?',
      'averageCycle': 'Average Cycle',
      'cycleConsistency': 'Cycle Consistency',
      'longestCycle': 'Longest Cycle',
      'shortestCycle': 'Shortest Cycle',
      'currentPhaseDuration': 'Current Phase',
      'noCycleData': 'No cycle data available',
      'trackPeriodHint': 'Track your period by tapping a date on the calendar',
      'logMoreMoods': 'Log more moods to see patterns',
      'errorGeneric': 'Something went wrong',
      'errorNoData': 'No data available',
      'welcomeTitle': 'Welcome to Floii!',
      'welcomeSubtitle':
          'Start tracking your period to see personalized insights and predictions.',
      'welcomeHint':
          'Tap on any date in the calendar to start tracking your period.',
      'expectedSoon': 'Expected Soon',
      'periodExpected': 'Period Expected',
      'periodExpectedToday': 'Your period is expected today',
      'periodExpectedTomorrow': 'Your period is expected tomorrow',
      'In': 'In',
      'days': 'days',
      'expectedDate': 'Expected Date',
      'helpAndFaq': 'Help & FAQ',
      'about': 'About',
      'sendFeedback': 'Send Feedback',
      'language': 'Language',
      'chooseLanguage': 'Choose your preferred language',
      'theme': 'Theme',
      'dark': 'Dark',
      'light': 'Light',
      'factoryReset': 'Factory Reset',
      'deleteAllData': 'Delete all data and settings',
      'allDataDeleted': 'All data has been deleted',
      'version': 'Version',
      'general': 'General',
      'support': 'Support',
      'dangerZone': 'Danger Zone',
      'cyclePhases': 'Cycle Phases',
      'trackYourJourney': 'Track your journey through each phase',
      'period': 'Period',
      'fertile': 'Fertile',
      'predicted': 'Predicted',
      'today': 'Today',
      "stillNeedHelp": "Still need help",
      "contact": "Contact us through the Send Feedback option in settings.",
      'feedbackThankYou': 'Thank you for your feedback!',
      'feedbackDescription':
          'Your feedback helps us improve Floii and make it better for everyone.',
      'thankYouExclamation': 'Thank you!',
      'weReadEveryFeedback':
          'We read every piece of feedback and use it to make Floii better.',
      'nameOptional': 'Name (Optional)',
      'enterYourName': 'Enter your name',
      'emailOptional': 'Email (Optional)',
      'enterYourEmail': 'Enter your email',
      'yourFeedback': 'Your Feedback *',
      'tellUsWhatYouThink': 'Tell us what you think...',
      'pleaseEnterFeedback': 'Please enter your feedback',
      'feedbackMinLength': 'Feedback must be at least 10 characters',
      'sending': 'Sending...',
      'weLoveToHearFromYou': 'We\'d love to hear from you!',
      'stats': 'Statistics',
      'phaseBreakdown': 'Phase Breakdown',
      'fertForcast': 'Fertility Forecast',
      'q1': 'How do I track my period?',
      'a1':
          'Simply tap on any date in the calendar to mark it as your period start date. You can also tap and hold to edit or remove period dates.',
      'q2': 'How are predictions calculated?',
      'a2':
          '${AppStrings.appName} uses your cycle history to predict future periods. The more data you track, the more accurate the predictions become.',
      'q3': 'What do the different colors mean?',
      'a3':
          'Pink indicates your period, green shows fertile days, orange marks ovulation, and purple highlights predicted periods.',
      'q4': 'Can I export my data?',
      'a4':
          'Currently, data export is not available. We recommend taking screenshots of important information. This feature will be added in a future update.',
      'q5': 'Is my data private?',
      'a5':
          'Yes! All your data is stored locally on your device. ${AppStrings.appName} does not send any personal information to external servers.',
      'q6': 'How do I delete my data?',
      'a6':
          'Go to Settings > Danger Zone > Factory Reset to delete all your data. This action cannot be undone.',
    },
    'ar': {
      'appName': 'فلوي',
      'appTagline': 'تتبع دورتك بسهولة',
      'home': 'الرئيسية',
      'insights': 'التحليلات',
      'settings': 'الإعدادات',
      'history': 'التاريخ',
      'currentPhase': 'المرحلة الحالية',
      'phase': 'المرحلة',
      'current': 'الحالية',
      'cycle': 'دورة',
      'nextPeriod': 'الدورة القادمة',
      'cycleProgress': 'تقدم الدورة',
      'Day': 'يوم',
      'of': 'من',
      'left': 'بقي',
      'clear': 'حذف',
      'Upcoming': 'قادمة',
      'duration': 'مدة',
      'menstrualPhase': 'الحيض',
      'follicularPhase': 'الجريبي',
      'ovulationPhase': 'الإباضة',
      'lutealPhase': 'الأصفر',
      'menstrualDescription': 'الشهية والتعب ممكنان',
      'follicularDescription': 'الإنتاجية والإبداع ممكنان',
      'ovulationDescription': 'ذروة الخصوبة والطاقة',
      'lutealDescription': 'تقلبات المزاج والحساسية',
      'nullDescription': 'تتبعي دورتك الشهرية للحصول على معلومات شخصية',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'confirm': 'تأكيد',
      'accept': 'قبول',
      'trackToday': 'تتبع اليوم',
      'trackMyPeriod': 'تتبع دورتي',
      'confirmPrediction': 'تأكيد التوقع',
      'acceptPredictedPeriod': 'قبول الدورة المتوقعة بدءًا من {date}؟',
      'startPeriod': 'بدء الدورة؟',
      'startPeriodMessage': 'هل بدأت دورتك في {date}؟',
      'editPeriod': 'تعديل الدورة',
      'periodSettings': 'إعدادات الدورة',
      'menstrualDaysQuestion': 'كم يوماً تستمر دورتك الشهرية عادة؟',
      'averageCycle': 'متوسط الدورة',
      'cycleConsistency': 'انتظام الدورة',
      'longestCycle': 'أطول دورة',
      'shortestCycle': 'أقصر دورة',
      'currentPhaseDuration': 'المرحلة الحالية',
      'noCycleData': 'لا توجد بيانات دورة متاحة',
      'trackPeriodHint': 'تتبع دورتك بالنقر على تاريخ في التقويم',
      'logMoreMoods': 'سجل المزيد من الحالات المزاجية لرؤية الأنماط',
      'errorGeneric': 'حدث خطأ ما',
      'errorNoData': 'لا توجد بيانات متاحة',
      'welcomeTitle': 'مرحباً بك في فلوي!',
      'welcomeSubtitle': 'ابدأ بتتبع دورتك لرؤية رؤى وتوقعات مخصصة.',
      'welcomeHint': 'انقر على أي تاريخ في التقويم لبدء تتبع دورتك.',
      'expectedSoon': 'متوقع قريباً',
      'periodExpected': 'الدورة متوقعة',
      'periodExpectedToday': 'الدورة متوقعة اليوم',
      'periodExpectedTomorrow': 'الدورة متوقعة غداً',
      'days': 'أيام بعد',
      'expectedDate': 'التاريخ المتوقع',
      'helpAndFaq': 'المساعدة',
      "Faq": "أسئلة مكررة",
      'about': 'حول',
      'sendFeedback': 'إرسال ملاحظات',
      'language': 'اللغة',
      'chooseLanguage': 'اختر لغتك المفضلة',
      'theme': 'المظهر',
      'dark': 'داكن',
      'light': 'فاتح',
      'factoryReset': 'إعادة ضبط المصنع',
      'deleteAllData': 'حذف جميع البيانات والإعدادات',
      'allDataDeleted': 'تم حذف جميع البيانات',
      'version': 'الإصدار',
      'general': 'عام',
      'support': 'الدعم',
      'dangerZone': 'منطقة الخطر',
      'cyclePhases': 'مراحل الدورة',
      'trackYourJourney': 'تتبع رحلتك عبر كل مرحلة',
      'period': 'الحيض',
      'fertile': 'الخصوبة',
      'predicted': 'المتوقع',
      'today': 'اليوم',
      "stillNeedHelp": "هل لا تزال بحاجة للمساعدة؟",
      "contact": "تواصل معنا من خلال خيار 'إرسال ملاحظات' في الإعدادات.",
      'feedbackThankYou': '!شكراً لملاحظاتك',
      'feedbackDescription':
          'تساعدنا ملاحظاتك على تحسين فلوي وجعله أفضل للجميع.',
      'thankYouExclamation': 'شكراً لك!',
      'weReadEveryFeedback': 'نقرأ كل ملاحظة ونستخدمها لجعل فلوي أفضل.',
      'nameOptional': 'الاسم (اختياري)',
      'enterYourName': 'أدخل اسمك',
      'emailOptional': 'البريد الإلكتروني (اختياري)',
      'enterYourEmail': 'أدخل بريدك الإلكتروني',
      'yourFeedback': 'ملاحظاتك *',
      'tellUsWhatYouThink': 'أخبرنا بما تفكر فيه...',
      'pleaseEnterFeedback': 'الرجاء إدخال ملاحظاتك',
      'feedbackMinLength': 'يجب أن تكون الملاحظات 10 أحرف على الأقل',
      'sending': 'جاري الإرسال...',
      'weLoveToHearFromYou': 'نود أن نسمع منك!',
      'stats': 'إحصائيات',
      'phaseBreakdown': 'انهيار المرحلة',
      'fertForcast': 'توقعات الخصوبة',
      'q1': 'كيف يمكنني تتبع دورتي الشهرية؟',
      'a1':
          'ببساطة، اضغطي على أي تاريخ في التقويم لتحديد بدء دورتك. يمكنك أيضاً الضغط مطولاً لتعديل أو حذف التواريخ.',
      'q2': 'كيف يتم حساب التوقعات؟',
      'a2':
          'يستخدم ${AppStrings.appName} سِجل دورتك للتنبؤ بالدورات المستقبلية. كلما قمتِ بتسجيل بيانات أكثر، أصبحت التوقعات أكثر دقة.',
      'q3': 'ماذا تعني الألوان المختلفة؟',
      'a3':
          'يشير الوردي إلى دورتك الشهرية، والأخضر للأيام الخصبة، والبرتقالي للإباضة، والبنفسجي للدورة المتوقعة.',
      'q4': 'هل يمكنني تصدير بياناتي؟',
      'a4':
          'تصدير البيانات غير متاح حالياً. ننصح بأخذ لقطات شاشة للمعلومات المهمة. سيتم إضافة هذه الميزة في تحديث مستقبلي.',
      'q5': 'هل بياناتي خاصة؟',
      'a5':
          'نعم! يتم تخزين جميع بياناتك محلياً على جهازك. لا يقوم ${AppStrings.appName} بإرسال أي معلومات شخصية إلى خوادم خارجية.',
      'q6': 'كيف أحذف بياناتي؟',
      'a6':
          'انتقلي إلى الإعدادات > منطقة الخطر > ضبط المصنع لحذف جميع بياناتك. لا يمكن التراجع عن هذا الإجراء.',
    },
    'ur': {
      'appName': 'فلوئی',
      'appTagline': 'آسانی سے اپنا سائکل ٹریک کریں',
      'home': 'ہوم',
      'insights': 'تجزیہ',
      'settings': 'سیٹنگز',
      'history': 'تاریخ',
      'currentPhase': 'موجودہ مرحلہ',
      'phase': 'مرحلہ',
      'current': 'موجودہ',
      'cycle': 'دور',
      'nextPeriod': 'اگلا پیریڈ',
      'cycleProgress': 'سائکل کی پیشرفت',
      'Day': 'دن',
      'of': 'باقی',
      'In': 'میں',
      'left': 'باقی',
      'clear': 'حذف کریں',
      'Upcoming': 'آنے والا',
      'duration': 'دورانیہ',
      'menstrualPhase': 'حیض',
      'follicularPhase': 'فولیکیولر',
      'ovulationPhase': 'بیضہ دانی',
      'lutealPhase': 'لیوٹیل',
      'menstrualDescription': 'خواہشات اور تھکاوٹ ممکن ہیں',
      'follicularDescription': 'پیداواری صلاحیت اور تخلیقیت ممکن ہے',
      'ovulationDescription': 'زائد بیضہ دہی اور توانائی کا عروج',
      'lutealDescription': 'مزاج میں اتار چڑھاؤ اور حساسیت',
      'nullDescription': 'ذاتی بصیرت کے لیے اپنے سائیکل کو ٹریک کریں۔',
      'save': 'محفوظ کریں',
      'cancel': 'منسوخ کریں',
      'delete': 'حذف کریں',
      'confirm': 'تصدیق کریں',
      'accept': 'قبول کریں',
      'trackToday': 'آج ٹریک کریں',
      'trackMyPeriod': 'میرا پیریڈ ٹریک کریں',
      'confirmPrediction': 'پیشن گوئی کی تصدیق کریں',
      'acceptPredictedPeriod':
          '{date} سے شروع ہونے والی متوقع پیریڈ قبول کریں؟',
      'startPeriod': 'پیریڈ شروع کریں؟',
      'startPeriodMessage': 'کیا آپ کا پیریڈ {date} کو شروع ہوا؟',
      'editPeriod': 'پیریڈ میں ترمیم کریں',
      'periodSettings': 'پیریڈ کی سیٹنگز',
      'menstrualDaysQuestion': 'آپ کے پیریڈ میں عام طور پر کتنے دن ہوتے ہیں؟',
      'averageCycle': 'اوسط سائکل',
      'cycleConsistency': 'سائکل کی مستقل مزاجی',
      'longestCycle': 'سب سے لمبا سائکل',
      'shortestCycle': 'سب سے مختصر سائکل',
      'currentPhaseDuration': 'موجودہ مرحلہ',
      'noCycleData': 'کوئی سائکل ڈیٹا دستیاب نہیں ہے',
      'trackPeriodHint':
          'کیلنڈر میں کسی تاریخ پر ٹیپ کرکے اپنا پیریڈ ٹریک کریں',
      'logMoreMoods': 'پیٹرن دیکھنے کے لیے مزید موڈز لاگ کریں',
      'errorGeneric': 'کچھ غلط ہو گیا',
      'errorNoData': 'کوئی ڈیٹا دستیاب نہیں ہے',
      'welcomeTitle': 'فلوئی میں خوش آمدید!',
      'welcomeSubtitle':
          'ذاتی نوعیت کے تجزیات اور پیشن گوئی دیکھنے کے لیے اپنا پیریڈ ٹریک کرنا شروع کریں۔',
      'welcomeHint':
          'اپنا پیریڈ ٹریک کرنا شروع کرنے کے لیے کیلنڈر میں کسی بھی تاریخ پر ٹیپ کریں۔',
      'expectedSoon': 'جلد متوقع ہے',
      'periodExpected': 'پیریڈ متوقع ہے',
      'periodExpectedToday': 'آج آپ کا پیریڈ متوقع ہے',
      'periodExpectedTomorrow': 'کل آپ کا پیریڈ متوقع ہے',
      'days': 'دنوں',
      'expectedDate': 'متوقع تاریخ',
      'helpAndFaq': 'مدد',
      "Faq": "اکثر پوچھے گئے سوالات",
      'about': 'ہمارے بارے میں',
      'sendFeedback': 'رائے بھیجیں',
      'language': 'زبان',
      'chooseLanguage': 'اپنی پسندیدہ زبان منتخب کریں',
      'theme': 'تھیم',
      'dark': 'تاریک',
      'light': 'روشن',
      'factoryReset': 'فیکٹری ری سیٹ',
      'deleteAllData': 'تمام ڈیٹا اور سیٹنگز حذف کریں',
      'allDataDeleted': 'تمام ڈیٹا حذف کر دیا گیا ہے',
      'version': 'ورژن',
      'general': 'عام',
      'support': 'سپورٹ',
      'dangerZone': 'خطرے کا علاقہ',
      'cyclePhases': 'سائکل کے مراحل',
      'trackYourJourney': 'ہر مرحلے میں اپنی سفر کو ٹریک کریں',
      'period': 'پیریڈ',
      'fertile': 'زرخیز',
      'predicted': 'متوقع',
      'today': 'آج',
      "stillNeedHelp": "کیا آپ کو مزید مدد کی ضرورت ہے؟",
      "contact":
          "سیٹنگز میں 'فیڈ بیک بھیجیں' کے آپشن کے ذریعے ہم سے رابطہ کریں۔",
      'feedbackThankYou': 'آپ کی رائے کا شکریہ!',
      'feedbackDescription':
          'آپ کی رائے ہمیں فلوئی کو بہتر بنانے اور سب کے لیے بہتر بنانے میں مدد کرتی ہے۔',
      'thankYouExclamation': 'شکریہ!',
      'weReadEveryFeedback':
          'ہم ہر رائے پڑھتے ہیں اور اسے فلوئی کو بہتر بنانے کے لیے استعمال کرتے ہیں۔',
      'nameOptional': 'نام (اختیاری)',
      'enterYourName': 'اپنا نام درج کریں',
      'emailOptional': 'ای میل (اختیاری)',
      'enterYourEmail': 'اپنا ای میل درج کریں',
      'yourFeedback': 'آپ کی رائے *',
      'tellUsWhatYouThink': 'ہمیں بتائیں کہ آپ کیا سوچتے ہیں...',
      'pleaseEnterFeedback': 'براہ کرم اپنی رائے درج کریں',
      'feedbackMinLength': 'رائے کم از کم 10 حروف کی ہونی چاہیے',
      'sending': ' بھیج رہا ہے...',
      'weLoveToHearFromYou': 'ہم آپ سے سننا پسند کریں گے!',
      'stats': 'شماریات',
      'phaseBreakdown': 'فیز بریک ڈاؤن',
      'fertForcast': 'زرخیزی کی پیشن گوئی',
      'q1': 'میں اپنی ماہواری کیسے ٹریک کروں؟',
      'a1':
          'ماہواری کی شروعات کو مارک کرنے کے لیے کیلنڈر پر کسی بھی تاریخ پر ٹیپ کریں۔ تواریخ میں ترمیم یا حذف کرنے کے لیے دبا کر رکھیں۔',
      'q2': 'پیشین گوئیاں کیسے کی جاتی ہیں؟',
      'a2':
          '${AppStrings.appName} آپ کی ہسٹری استعمال کر کے اگلی ماہواری کی پیشین گوئی کرتا ہے۔ جتنا زیادہ ڈیٹا آپ ٹریک کریں گی، پیشین گوئی اتنی ہی درست ہوگی۔',
      'q3': 'مختلف رنگوں کا کیا مطلب ہے؟',
      'a3':
          'گلابی رنگ ماہواری، سبز زرخیز دنوں، نارنجی اوولیشن، اور جامنی رنگ متوقع ماہواری کی نشاندہی کرتا ہے۔',
      'q4': 'کیا میں اپنا ڈیٹا ایکسپورٹ کر سکتی ہوں؟',
      'a4':
          'فی الحال ڈیٹا ایکسپورٹ کی سہولت دستیاب نہیں ہے۔ ہم مشورہ دیتے ہیں کہ آپ اہم معلومات کے سکرین شاٹس لے لیں۔ یہ فیچر مستقبل میں شامل کر دیا جائے گا۔',
      'q5': 'کیا میرا ڈیٹا نجی ہے؟',
      'a5':
          'جی ہاں! آپ کا تمام ڈیٹا مقامی طور پر آپ کے فون میں محفوظ ہوتا ہے۔ ${AppStrings.appName} کوئی بھی ذاتی معلومات بیرونی سرورز پر نہیں بھیجتا۔',
      'q6': 'میں اپنا ڈیٹا کیسے حذف کروں؟',
      'a6':
          'تمام ڈیٹا حذف کرنے کے لیے سیٹنگز > ڈینجر زون > فیکٹری ری سیٹ پر جائیں۔ یہ عمل ناقابل واپسی ہے۔',
    },
    'id': {
      'appName': 'Floii',
      'appTagline': 'Lacak siklusmu dengan mudah',
      'home': 'Beranda',
      'insights': 'Wawasan',
      'settings': 'Pengaturan',
      'history': 'Sejarah',
      'currentPhase': 'Fase Saat Ini',
      'phase': 'Fase',
      'current': 'Saat Ini',
      'cycle': 'Siklus',
      'nextPeriod': 'Menstruasi Berikutnya',
      'cycleProgress': 'Progres Siklus',
      'Day': 'Hari ke',
      'of': 'dari',
      'left': 'lagi',
      'clear': 'menghapus',
      'Upcoming': 'Mendatang',
      'duration': 'Lamanya',
      'menstrualPhase': 'Menstruasi',
      'follicularPhase': 'Folikular',
      'ovulationPhase': 'Ovulasi',
      'lutealPhase': 'Luteal',
      'menstrualDescription': 'Nafsu makan dan kelelahan mungkin terjadi',
      'follicularDescription':
          'Produktivitas dan kreativitas mungkin meningkat',
      'ovulationDescription': 'Puncak kesuburan dan energi',
      'lutealDescription': 'Perubahan suasana hati & sensitivitas',
      'nullDescription':
          'Lacak siklus Anda untuk mendapatkan wawasan yang dipersonalisasi.',
      'save': 'Simpan',
      'cancel': 'Batal',
      'delete': 'Hapus',
      'confirm': 'Konfirmasi',
      'accept': 'Terima',
      'trackToday': 'Lacak Hari Ini',
      'trackMyPeriod': 'Lacak Menstruasi Saya',
      'confirmPrediction': 'Konfirmasi Prediksi',
      'acceptPredictedPeriod':
          'Terima Menstruasi yang diprediksi mulai dari {date}?',
      'startPeriod': 'Mulai Menstruasi?',
      'startPeriodMessage': 'Apakah Menstruasi Anda dimulai pada {date}?',
      'editPeriod': 'Edit Menstruasi',
      'periodSettings': 'Pengaturan Menstruasi',
      'menstrualDaysQuestion':
          'Berapa hari Menstruasi Anda biasanya berlangsung?',
      'averageCycle': 'Siklus Rata-rata',
      'cycleConsistency': 'Konsistensi Siklus',
      'longestCycle': 'Siklus Terpanjang',
      'shortestCycle': 'Siklus Terpendek',
      'currentPhaseDuration': 'Fase Saat Ini',
      'noCycleData': 'Tidak ada data siklus tersedia',
      'trackPeriodHint':
          'Lacak Menstruasi Anda dengan mengetuk tanggal di kalender',
      'logMoreMoods': 'Catat lebih banyak suasana hati untuk melihat pola',
      'errorGeneric': 'Terjadi kesalahan',
      'errorNoData': 'Tidak ada data tersedia',
      'welcomeTitle': 'Selamat Datang di Floii!',
      'welcomeSubtitle':
          'Mulai lacak Menstruasi Anda untuk melihat wawasan dan prediksi yang dipersonalisasi.',
      'welcomeHint':
          'Ketuk tanggal apa pun di kalender untuk mulai melacak Menstruasi Anda.',
      'expectedSoon': 'Diharapkan Segera',
      'periodExpected': 'Menstruasi Diharapkan',
      'periodExpectedToday': 'Menstruasi Anda diharapkan hari ini',
      'periodExpectedTomorrow': 'Menstruasi Anda diharapkan besok',
      'In': 'Dalam',
      'days': 'hari',
      'expectedDate': 'Tanggal Diharapkan',
      'helpAndFaq': 'Bantuan & FAQ',
      "Faq": "Pertanyaan Umum",
      'about': 'Tentang',
      'sendFeedback': 'Kirim Umpan Balik',
      'language': 'Bahasa',
      'chooseLanguage': 'Pilih bahasa pilihan Anda',
      'theme': 'Tema',
      'dark': 'Gelap',
      'light': 'Terang',
      'factoryReset': 'Reset Pabrik',
      'deleteAllData': 'Hapus semua data dan pengaturan',
      'allDataDeleted': 'Semua data telah dihapus',
      'version': 'Versi',
      'general': 'Umum',
      'support': 'Dukungan',
      'dangerZone': 'Zona Berbahaya',
      'cyclePhases': 'Fase Siklus',
      'trackYourJourney': 'Lacak perjalanan Anda melalui setiap fase',
      'period': 'Menstruasi',
      'fertile': 'Subur',
      'predicted': 'Prediksi',
      'today': 'Hari Ini',
      "stillNeedHelp": "Masih butuh bantuan?",
      "contact": "Hubungi kami melalui opsi 'Kirim Masukan' di pengaturan.",
      'feedbackThankYou': 'Terima kasih atas umpan balik Anda!',
      'feedbackDescription':
          'Umpan balik Anda membantu kami meningkatkan Floii dan menjadikannya lebih baik untuk semua orang.',
      'thankYouExclamation': 'Terima kasih!',
      'weReadEveryFeedback':
          'Kami membaca setiap umpan balik dan menggunakannya untuk membuat Floii lebih baik.',
      'nameOptional': 'Nama (Opsional)',
      'enterYourName': 'Masukkan nama Anda',
      'emailOptional': 'Email (Opsional)',
      'enterYourEmail': 'Masukkan email Anda',
      'yourFeedback': 'Umpan Balik Anda *',
      'tellUsWhatYouThink': 'Beri tahu kami apa yang Anda pikirkan...',
      'pleaseEnterFeedback': 'Silakan masukkan umpan balik Anda',
      'feedbackMinLength': 'Umpan balik minimal harus 10 karakter',
      'sending': 'Mengirim...',
      'weLoveToHearFromYou': 'Kami ingin mendengar dari Anda!',
      'stats': 'Statistik',
      'phaseBreakdown': 'Perincian Fase',
      'fertForcast': 'Prakiraan Kesuburan',
      'q1': 'Bagaimana cara melacak haid saya?',
      'a1':
          'Cukup ketuk tanggal mana pun di kalender untuk menandainya sebagai awal haid. Anda juga bisa menekan dan menahan untuk mengedit atau menghapus tanggal.',
      'q2': 'Bagaimana prediksi dihitung?',
      'a2':
          '${AppStrings.appName} menggunakan riwayat siklus Anda untuk memprediksi haid di masa depan. Semakin banyak data yang Anda lacak, semakin akurat prediksinya.',
      'q3': 'Apa arti warna-warna tersebut?',
      'a3':
          'Merah muda menandakan haid, hijau menunjukkan masa subur, oranye menandai ovulasi, dan ungu menyoroti prediksi haid.',
      'q4': 'Bisakah saya mengekspor data saya?',
      'a4':
          'Saat ini, ekspor data belum tersedia. Kami menyarankan untuk mengambil tangkapan layar (screenshot) informasi penting. Fitur ini akan ditambahkan pada pembaruan mendatang.',
      'q5': 'Apakah data saya pribadi?',
      'a5':
          'Ya! Semua data Anda tersimpan secara lokal di perangkat Anda. ${AppStrings.appName} tidak mengirimkan informasi pribadi apa pun ke server eksternal.',
      'q6': 'Bagaimana cara menghapus data saya?',
      'a6':
          'Buka Pengaturan > Zona Bahaya > Reset Pabrik untuk menghapus semua data Anda. Tindakan ini tidak dapat dibatalkan.',
    },
    'de': {
      'appName': 'Floii',
      'appTagline': 'Verfolge deinen Zyklus mit Leichtigkeit',
      'home': 'Startseite',
      'insights': 'Einblicke',
      'settings': 'Einstellungen',
      'history': 'Verlauf',
      'currentPhase': 'Aktuelle Phase',
      'phase': 'Phase',
      'current': 'Current',
      'cycle': 'Zyklus',
      'nextPeriod': 'Nächste ',
      'cycleProgress': 'Zyklusfortschritt',
      'Day': 'Tag',
      'of': 'von',
      'left': 'übrig',
      'clear': 'löschen',
      'Upcoming': 'Kommende',
      'duration': 'Dauer',
      'menstrualPhase': 'Menstruation',
      'follicularPhase': 'Follikelphase',
      'ovulationPhase': 'Eisprung',
      'lutealPhase': 'Lutealphase',
      'menstrualDescription': 'Heißhunger und Müdigkeit möglich',
      'follicularDescription': 'Produktivität und Kreativität möglich',
      'ovulationDescription': 'Höchste Fruchtbarkeit und Energie',
      'lutealDescription': 'Stimmungsschwankungen & Sensitivität',
      'nullDescription': 'Verfolge deinen Zyklus für personalisierte Einblicke',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'confirm': 'Bestätigen',
      'accept': 'Akzeptieren',
      'trackToday': 'Heute verfolgen',
      'trackMyPeriod': 'Meine  verfolgen',
      'confirmPrediction': 'Vorhersage bestätigen',
      'acceptPredictedPeriod': 'Vorhergesagte  ab {date} akzeptieren?',
      'startPeriod': 'Periode beginnen?',
      'startPeriodMessage': 'Hat Ihre Periode am {date} begonnen?',
      'editPeriod': 'Periode bearbeiten',
      'periodSettings': 'Periodeneinstellungen',
      'menstrualDaysQuestion':
          'Wie viele Tage dauert Ihre Periode normalerweise an?',
      'averageCycle': 'Durchschnittlicher Zyklus',
      'cycleConsistency': 'Zykluskonsistenz',
      'longestCycle': 'Längster Zyklus',
      'shortestCycle': 'Kürzester Zyklus',
      'currentPhaseDuration': 'Aktuelle Phase',
      'noCycleData': 'Keine Zyklusdaten verfügbar',
      'trackPeriodHint':
          'Verfolgen Sie Ihre Periode, indem Sie auf ein Datum im Kalender tippen',
      'logMoreMoods':
          'Protokollieren Sie mehr Stimmungen, um Muster zu erkennen',
      'errorGeneric': 'Etwas ist schiefgelaufen',
      'errorNoData': 'Keine Daten verfügbar',
      'welcomeTitle': 'Willkommen bei Floii!',
      'welcomeSubtitle':
          'Beginnen Sie mit der Verfolgung Ihrer Periode, um personalisierte Einblicke und Vorhersagen zu sehen.',
      'welcomeHint':
          'Tippen Sie auf ein beliebiges Datum im Kalender, um mit der Verfolgung Ihrer Periode zu beginnen.',
      'expectedSoon': 'Bald erwartet',
      'periodExpected': 'Periode erwartet',
      'periodExpectedToday': 'Ihre Periode wird heute erwartet',
      'periodExpectedTomorrow': 'Ihre Periode wird morgen erwartet',
      'In': 'InTagen',
      'days': 'Tagen',
      'expectedDate': 'Erwartetes Datum',
      'helpAndFaq': 'Hilfe & FAQ',
      "Faq": "Häufig gestellte Fragen",
      'about': 'Über',
      'sendFeedback': 'Feedback senden',
      'language': 'Sprache',
      'chooseLanguage': 'Wählen Sie Ihre bevorzugte Sprache',
      'theme': 'Thema',
      'dark': 'Dunkel',
      'light': 'Hell',
      'factoryReset': 'Werkseinstellungen',
      'deleteAllData': 'Alle Daten und Einstellungen löschen',
      'allDataDeleted': 'Alle Daten wurden gelöscht',
      'version': 'Version',
      'general': 'Allgemein',
      'support': 'Support',
      'dangerZone': 'Gefahrenzone',
      'cyclePhases': 'Zyklusphasen',
      'trackYourJourney': 'Verfolgen Sie Ihre Reise durch jede Phase',
      'period': 'die Periode',
      'fertile': 'Fruchtbar',
      'predicted': 'Vorhergesagt',
      'today': 'Heute',
      "stillNeedHelp": "Benötigen Sie weitere Hilfe?",
      "contact":
          "Kontaktieren Sie uns über die Option 'Feedback senden' in den Einstellungen.",
      'feedbackThankYou': 'Vielen Dank für Ihr Feedback!',
      'feedbackDescription':
          'Ihr Feedback hilft uns, Floii zu verbessern und es für alle besser zu machen.',
      'thankYouExclamation': 'Vielen Dank!',
      'weReadEveryFeedback':
          'Wir lesen jedes Feedback und nutzen es, um Floii besser zu machen.',
      'nameOptional': 'Name (Optional)',
      'enterYourName': 'Geben Sie Ihren Namen ein',
      'emailOptional': 'E-Mail (Optional)',
      'enterYourEmail': 'Geben Sie Ihre E-Mail ein',
      'yourFeedback': 'Ihr Feedback *',
      'tellUsWhatYouThink': 'Sagen Sie uns, was Sie denken...',
      'pleaseEnterFeedback': 'Bitte geben Sie Ihr Feedback ein',
      'feedbackMinLength': 'Feedback muss mindestens 10 Zeichen lang sein',
      'sending': 'Wird gesendet...',
      'weLoveToHearFromYou': 'Wir würden gerne von Ihnen hören!',
      'stats': 'Statistiken',
      'phaseBreakdown': 'Perincian Fase',
      'fertForcast': 'Fruchtbarkeitsprognose',
      'q1': 'Wie tracke ich meine Periode?',
      'a1':
          'Tippen Sie einfach auf ein Datum im Kalender, um es als Periodenstart zu markieren. Tippen und halten Sie, um Daten zu bearbeiten oder zu entfernen.',
      'q2': 'Wie werden Vorhersagen berechnet?',
      'a2':
          '${AppStrings.appName} nutzt Ihren Zyklusverlauf, um zukünftige Perioden vorherzusagen. Je mehr Daten Sie erfassen, desto genauer werden die Vorhersagen.',
      'q3': 'Was bedeuten die verschiedenen Farben?',
      'a3':
          'Rosa markiert Ihre Periode, Grün zeigt fruchtbare Tage, Orange steht für den Eisprung und Lila hebt vorhergesagte Perioden hervor.',
      'q4': 'Kann ich meine Daten exportieren?',
      'a4':
          'Der Datenexport ist derzeit nicht verfügbar. Wir empfehlen, Screenshots von wichtigen Informationen zu machen. Diese Funktion wird in einem zukünftigen Update hinzugefügt.',
      'q5': 'Sind meine Daten privat?',
      'a5':
          'Ja! Alle Ihre Daten werden lokal auf Ihrem Gerät gespeichert. ${AppStrings.appName} sendet keine persönlichen Informationen an externe Server.',
      'q6': 'Wie lösche ich meine Daten?',
      'a6':
          'Gehen Sie zu Einstellungen > Gefahrenzone > Werkseinstellungen, um alle Daten zu löschen. Dieser Vorgang kann nicht rückgängig gemacht werden.',
    },
  };

  String translate(String key) {
    final langTranslations = _translations[locale.languageCode];
    if (langTranslations == null) return key;
    return langTranslations[key] ?? _translations['en']![key] ?? key;
  }

  String translateWithArgs(String key, Map<String, dynamic> args) {
    String value = translate(key);
    args.forEach((argKey, argValue) {
      value = value.replaceAll('{$argKey}', argValue.toString());
    });
    return value;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar', 'ur', 'id', 'de'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
